apiVersion: v1
kind: Service
metadata:
  name: {{ include "tplink_smartplug_exporter.fullname" . }}
  labels:
    app: {{ .Release.Name }}
    release: {{ .Release.Name }}
    {{- include "tplink_smartplug_exporter.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "tplink_smartplug_exporter.selectorLabels" . | nindent 4 }}
